### ISSUE TITLE
Echo throws a TypeError

### ISSUE THREAD

**Issue by MrHDR** [GameboyDiscord/DMG-Bot#3]
```
TypeError: '>=' not supported between instances of 'Role' and 'NoneType'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 936, in on_message
    await self.process_commands(message)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 933, in process_commands
    await self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 898, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 608, in invoke
    await self.prepare(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 565, in prepare
    await self._verify_checks(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 518, in _verify_checks
    if not await self.can_run(ctx):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 816, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/usr/local/lib/python3.7/site-packages/discord/utils.py", line 282, in async_all
    for elem in gen:
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 816, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/pi/GameBoyBot/cogs/echo.py", line 28, in predicate
    return any([x >= role for x in msg.author.roles])
  File "/home/pi/GameBoyBot/cogs/echo.py", line 28, in <listcomp>
    return any([x >= role for x in msg.author.roles])
```

**Comment by MrHDR** [comment]
@Lett1
